@base_url = {{$dotenv REST_CLIENT_URL}}/api
@url={{base_url}}/rssi

GET {{url}}

###

GET {{url}}?page=1&count=5

###

GET {{url}}/id/1

###

GET {{url}}/detailed

###

POST {{url}}
Content-Type: application/json

{   
    "frequencyId": 1,
    "rssi": -40
}

###