@base_url = {{$dotenv REST_CLIENT_URL}}/api
@url={{base_url}}/reader-configuration

GET {{url}}

###

GET {{url}}?count=5

###

GET {{url}}?count=5&page=1

###

GET {{url}}?sortBy=id&sortOrder=asc

###

GET {{url}}?search=1

###

GET {{url}}/id/1

###

GET {{url}}/detailed

###

GET {{url}}/detailed?count=5

###

GET {{url}}/detailed?count=5&page=1

###

GET {{url}}/detailed?sortBy=id&sortOrder=asc

###

GET {{url}}/detailed?search=1

###

GET {{url}}/id/1/detailed

###

GET {{url}}/table

###

GET {{url}}/table?count=5

###

GET {{url}}/table?count=5&page=1

###

GET {{url}}/table?sortBy=id&sortOrder=asc

###

POST {{url}}
Content-Type: application/json

{
    "name": "Reader Configuration 1",
    "rssiScanCount": 5,
    "rssiScanInterval": 1000
}

###

PUT {{url}}/id/1
Content-Type: application/json

{
    "name": "Reader Configuration 1",
    "rssiScanCount": 5,
    "rssiScanInterval": 1000
}

###

DELETE {{url}}/id/1

###