@base_url = {{$dotenv REST_CLIENT_URL}}/api
@url={{base_url}}/active-reader-configuration

GET {{url}}

###

GET {{url}}?count=5

###

GET {{url}}?count=5&page=1

###

GET {{url}}?sortBy=id&sortOrder=asc

###

GET {{url}}/id/1

###

GET {{url}}/detailed

###

GET {{url}}/detailed?count=5

###

GET {{url}}/detailed?count=5&page=1

###

GET {{url}}/detailed?sortBy=id&sortOrder=asc

###

GET {{url}}/id/1/detailed

###

GET {{url}}/configuration

###

PUT {{url}}/id/1
Content-Type: application/json

{
    "readerConfigurationId": 1
}

###