@base_url = {{$dotenv REST_CLIENT_URL}}/api
@url={{base_url}}/frequency

GET {{url}}

###

GET {{url}}?count=5

###

GET {{url}}?count=5&page=1

###

GET {{url}}?sortBy=id&sortOrder=asc

###

GET {{url}}?search=1

###

GET {{url}}/id/1

###

GET {{url}}/detailed

###

GET {{url}}/detailed?count=5

###

GET {{url}}/detailed?count=5&page=1

###

GET {{url}}/detailed?sortBy=id&sortOrder=asc

###

GET {{url}}/detailed?search=1

###

GET {{url}}/id/1/detailed

###

GET {{url}}/table/tag-id/1

###

GET {{url}}/table/tag-id/1?count=5

###

GET {{url}}/table/tag-id/1?count=5&page=1

###

GET {{url}}/table/tag-id/1?sortBy=id&sortOrder=asc

###

POST {{url}}
Content-Type: application/json

{   
    "tagId": 1,
    "frequency": "192.5"
}

###