@base_url = {{$dotenv REST_CLIENT_URL}}/api
@url={{base_url}}/frequency-configuration

GET {{url}}

###

GET {{url}}?count=5

###

GET {{url}}?count=5&page=1

###

GET {{url}}?sortBy=id&sortOrder=asc

###

GET {{url}}?search=1

###

GET {{url}}/id/1

###

GET {{url}}/table/reader-configuration-id/1

###


GET {{url}}/table/reader-configuration-id/1?count=5

###

GET {{url}}/table/reader-configuration-id/1?count=5&page=1

###

GET {{url}}/table/reader-configuration-id/1?sortBy=id&sortOrder=asc

###


POST {{url}}
Content-Type: application/json

{
    "readerConfigurationId": 1,
    "frequency": "918"
}

###

PUT {{url}}/id/1
Content-Type: application/json

{
    "frequency": "918.5"
}

###

DELETE {{url}}/id/1

###