@base_url = {{$dotenv REST_CLIENT_URL}}/api
@url={{base_url}}/tag

GET {{url}}

###

GET {{url}}?page=1&count=5

###

GET {{url}}/id/1

###

GET {{url}}/detailed

###

GET {{url}}/detailed?page=1&count=5

###

GET {{url}}/id/1/detailed

###

POST {{url}}

###

PUT {{url}}/id/1
Content-Type: application/json

{
    "tag": "A0 B1 C2 D3 E4 F5"
}

###